### ISSUE TITLE
Impossible to edit entered value

### ISSUE THREAD

**Issue by Untit1ed** [mavDev/jquery.ipmask#4]
Can't edit any octets or when the whole input is selected it's impossible to type in a new value without clearing the old.

**Comment by mavDev** [comment]
Thank you, did not check the change octets. I'll try to fix it.

**Comment by mavDev** [comment]
Began to look for a solution and came across library http://robinherbots.github.io/jquery.inputmask/ There you can do the right mask for ip

**Comment by mavDev** [comment]
I added the ability to edit octetsю
